### ISSUE TITLE
Hot water current temperature is 0

### ISSUE THREAD

**Issue by en-ver** [rsciriano/ESPHome-OpenTherm#17]
In HA hot water current temp is 0 while I can see the correct temperature from the service menu on my boiler (Buderus Logamax U072)
Please advise how to fix it
![image](https://user-images.githubusercontent.com/10900846/145397280-abdf28e1-ee20-4e06-8a22-f2df363ba356.png)

**Comment by IvAn-source-git** [comment]
Hi. Do you have a single or double boiler? For single-loop, you need to edit the library OpenTherm.h
	Tr, // f8.8  Room temperature (°C)
	Tboiler, // f8.8  Boiler flow water temperature (°C)
	Tstorage, // f8.8  Solar storage temperature (°C)
	Toutside, // f8.8  Outside temperature (°C)
	Tret, // f8.8  Return water temperature (°C)
	Tdhw, // f8.8  DHW temperature (°C)

**Comment by enver-ablyaev** [comment]
@IvAn-source-git where this file is located? 
I can't find it in ESPHome-OpenTherm folder. 
Please advise.

**Comment by enver-ablyaev** [comment]
ok, from your repo I understood I simply can download it to my RPI and change it there.
but what exactly do I have to change there?

**Comment by IvAn-source-git** [comment]
Take everything from my repo. A lot has been fixed for our boiler (U)72 and Gaz60000)

**Comment by bartmarchand1** [comment]
@IvAn-source-git  what do you mean with a single or double loop?
I have a Bulex Thermomaster 28F, for heating and hot tap water production. Is this the double loop?

**Comment by IvAn-source-git** [comment]
The single-circuit boiler works with an indirect heating boiler for the preparation of hot water (for house). The double-circuit boiler produces hot water immediately (for appartement).

**Comment by IvAn-source-git** [comment]
For single-circuit boilers with an indirect heating boiler, the boiler outputs the DHW temperature in ID29.  There may be easier solutions, but I just changed "ID=26: DHW temperature"  and "ID=29: Solar storage temperature"

**Comment by enver-ablyaev** [comment]
@IvAn-source-git it didn't help

In addition, I found out that some other data is also absent
![image](https://user-images.githubusercontent.com/10900846/151992712-e1aa1164-d6ec-48ff-95aa-4c61cf53c7b7.png)

**Comment by IvAn-source-git** [comment]
Уже писал. Берите всё с моего репо.  Все котлы разные, со своими датчиками. Мой котел не передает внешнею температуру, давление, температуру обратки, соответственно эти запросы отключены.

**Comment by rsciriano** [comment]
Probably fixed by #52
