### ISSUE TITLE
Hot Water Thermostat not show status Work

### ISSUE THREAD

**Issue by Aliskin-Papa** [rsciriano/ESPHome-OpenTherm#2]
Hot Water Thermostat good work, but not change mode in the lovelas card to Work, any time show status Not Work.

**Comment by rsciriano** [comment]
Hi @Aliskin-Papa, in my boiler works. When I turn on the tap, the status changes

![image](https://user-images.githubusercontent.com/2356403/115765792-7c95f380-a3a7-11eb-9ba0-87bb352d220e.png)

The status is retrieved using the `isHotWaterActive` method of OpenTherm library, it is possible that your boiler does not return this information.

```
bool isHotWaterActive = ot.isHotWaterActive(response);
```

**Comment by Aliskin-Papa** [comment]
My boiler, Viessman Vitopend 100, can't return Pressure, Return temp and HotWaterActive. Its bad news for me...
Thanks to your work, its brilliant!

**Comment by Aliskin-Papa** [comment]
And one small question - how work switch Temperature ambiento?
