### ISSUE TITLE
 [RESOLVED] can't build with ESP Async WebServer

### ISSUE THREAD

**Issue by flodus** [rsciriano/ESPHome-OpenTherm#20]
Hello,

Thanks for your work !
When I try to build bin file with the default configuration I've got an error with the ESP Async WebServer library :

`
In file included from /data/opentherm/.piolibdeps/opentherm/ESP Async WebServer/src/AsyncEventSource.h:29:0,
                 from /data/opentherm/.piolibdeps/opentherm/ESP Async WebServer/src/AsyncEventSource.cpp:21:
/data/opentherm/.piolibdeps/opentherm/ESP Async WebServer/src/ESPAsyncWebServer.h:35:25: fatal error: ESP8266WiFi.h: No such file or directory

*********************************************************************
* Looking for ESP8266WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ESP8266WiFi.h"
* Web  > https://platformio.org/lib/search?query=header:ESP8266WiFi.h
*
*********************************************************************

 #include <ESP8266WiFi.h>
`

But if, in opentherm.yaml, I change "ESP Async WebServer" by "esphome/ESPAsyncWebServer-esphome @ 2.1.0" it seems to work for building bin file.
I don't know if you are aware of this error, or if it is only me who is confronted with this error.

Thanks again for your work !
Version of homeassistant : Home Assistant 2021.12.6
Version of esphome :  v2021.12.1

**Comment by HelpITru** [comment]
> Hello,
> 
> Thanks for your work ! When I try to build bin file with the default configuration I've got an error with the ESP Async WebServer library :
> 
> ` In file included from /data/opentherm/.piolibdeps/opentherm/ESP Async WebServer/src/AsyncEventSource.h:29:0, from /data/opentherm/.piolibdeps/opentherm/ESP Async WebServer/src/AsyncEventSource.cpp:21: /data/opentherm/.piolibdeps/opentherm/ESP Async WebServer/src/ESPAsyncWebServer.h:35:25: fatal error: ESP8266WiFi.h: No such file or directory
> 
>     * Looking for ESP8266WiFi.h dependency? Check our library registry!
> 
>     * CLI  > platformio lib search "header:ESP8266WiFi.h"
> 
>     * Web  > https://platformio.org/lib/search?query=header:ESP8266WiFi.h
> 
> 
> #include <ESP8266WiFi.h> `
> 
> But if, in opentherm.yaml, I change "ESP Async WebServer" by "esphome/ESPAsyncWebServer-esphome @ 2.1.0" it seems to work for building bin file. I don't know if you are aware of this error, or if it is only me who is confronted with this error.
> 
> Thanks again for your work ! Version of homeassistant : Home Assistant 2021.12.6 Version of esphome : v2021.12.1

Thanks ! It work for me
