### ISSUE TITLE
Home Assistant Integration (LoveLace)

### ISSUE THREAD

**Issue by electricfire** [rsciriano/ESPHome-OpenTherm#22]
Hi so i have flashed my esp8266 and all looks ok (FYI i dont have the opentherm connected as i have not received it yet) I can add the device to my integrations but i don't see the additional properties see below 

![image](https://user-images.githubusercontent.com/4716809/148424895-cec73ca4-cee9-4306-99be-2989df3e3033.png)
![image](https://user-images.githubusercontent.com/4716809/148425011-90e12200-c59e-45b9-b5ba-b95778bc32ff.png)

Is it because there is no opentherm connected which i find hard to believe or is there something missing?

Also on a separate note i am looking to upgrade my heating any advice on a boiler system / brand that will be compatible with this?

**Comment by rsciriano** [comment]
Hi @electricfire,

This happens because the opentherm adapter is not connected.

If you want to test without connecting it you can change line 35 of the `opentherm_component.h` file by increasing the polling time. 

```
  OpenthermComponent(): PollingComponent(10000) {
```

**Comment by electricfire** [comment]
Awesome thank you so much!!
