### ISSUE TITLE
unstable operation

### ISSUE THREAD

**Issue by bartmarchand1** [rsciriano/ESPHome-OpenTherm#25]
The following frequently occurs, always for a brief moment:
- Return temperature goes to -1°C 
- Hot water measurement goes to -1°C
- Heating water measurement (boiler temperature) goes to 0°C or 100°C
- All or some values are unavailable: when this occur, the logging pauzes for a while.
This behaviour is also in the log.

The device is not restarting, there are no wifi issues.
There are many debug messages per second.
Sometimes warning also: [13:04:29][W][pid.climate:122]: For PID autotuner you need to set AUTO (also called heat/cool) mode!
INFO opentherm.local: Ping timed out!
INFO Disconnected from ESPHome API for opentherm.local
WARNING Disconnected from API
INFO Successfully connected to opentherm.local

**Comment by rsciriano** [comment]
Probably fixed by #52
