### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by megavolt163** [rsciriano/ESPHome-OpenTherm#30]
I have a problem with compiling:

[logs_opentherm_upload.txt](https://github.com/rsciriano/ESPHome-OpenTherm/files/8273277/logs_opentherm_upload.txt)

can you help me?

**Comment by ShurikenGitHub** [comment]
Seems to be a broken/corrupted ESP8266WiFi.h library. You can try to reinstall Esphome. Maybe you can open an issue on the Esphome github page?
