### ISSUE TITLE
No entities in HA after successful configuration of discovered device

### ISSUE THREAD

**Issue by Toets** [rsciriano/ESPHome-OpenTherm#40]
The device is being discovered by HA. After clicking the Submit button in order to make the device available in HA the device appears but does not contain any entities. Note that the adapter is not yet connected to the opentherm bus but I can see sensors etc in the log made in ESPhome (see below)

[logs_opentherm_upload.txt](https://github.com/rsciriano/ESPHome-OpenTherm/files/10098604/logs_opentherm_upload.txt)

**Comment by Toets** [comment]
Found answer in previous case

**Comment by ov1d1u** [comment]
What was the solution?

**Comment by VladaDHS** [comment]
Hi find solution in other topic:
https://github.com/rsciriano/ESPHome-OpenTherm/issues/28#issuecomment-1051104594
