### ISSUE TITLE
Does not remember the last state after a reboot

### ISSUE THREAD

**Issue by tizenmile** [rsciriano/ESPHome-OpenTherm#42]
esp does not remember the last state after a reboot,
I live in a place where the lights are often turned off, so if the ESP gets clogged at night, the house will be very cold in the morning.
sorry for english, translated by google translate

**Comment by Chupaka** [comment]
I believe, this at the top of your YAML file is what you're looking for:

```
esp8266:
  restore_from_flash: true
```

**Comment by tizenmile** [comment]
Finally! Thanks for the help!
In my case I added this
```
esphome:
  esp8266_restore_from_flash: true
```
