### ISSUE TITLE
Hot water pressure -1

### ISSUE THREAD

**Issue by markobel** [rsciriano/ESPHome-OpenTherm#43]
On my installation the sensor Heating Water Pressure mark always -1.
As my understanding from the code is because the reading get a non valid response.
It would be possible that on my boiler the data have a different MessageID ?
Or more simply my boiler doesn't send this value to the opentherm bus ?

**Comment by Chupaka** [comment]
> Or more simply my boiler doesn't send this value to the opentherm bus ?

I vote this. E.g., my Bosch Gaz 6000 has only mechanical pressure sensor, so it cannot report pressure via OpenTherm.

**Comment by rsciriano** [comment]
Probably fixed by #52
